version: '3'

services:
    django:
        build:
            dockerfile: Dockerfile
            context: .
        command: bash -c "./manage.py migrate && 
                          ./manage.py runserver 0.0.0.0:8000"
        container_name: django_channels
        ports:
            - '8000:8000'
        volumes:
            - ./:/home/user/app
    redis:
        container_name: redis
        image: redis:5
        ports:
            - '6379:6379'
